[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
asyncio_mode = auto

[coverage:run]
source = app
omit =
    app/__init__.py
    migrations/*

[coverage:report]
fail_under = 75
show_missing = true
